### ISSUE TITLE
Example with .drive is wrong.

### ISSUE THREAD

**Issue by farafiri** [360fun/sbrick.js#8]
SBRICK1.drive( SBRICK1.CHANNEL0, SBRICK1.CW, SBRICK1.MAX );
didn't work for me. I had to use PORT0 constant instead of CHANNEL0

**Comment by 360fun** [comment]
I completely forgot to update the guide, thanks to remind me! ;)
Let me know if something else is missing please, it has passed a lot of time and I don't remember how much stuff I changed since the beginning: thanks!
